name: 🤖 Setup Android
description: Setup Android build tools

inputs:
  android-version:
    description: Android version
    required: true
    default: "34"
  build-tools-version:
    description: Build tools version https://developer.android.com/tools/releases/build-tools
    required: true
    default: 34.0.0
  cmd-line-version:
    description: Command line tools https://developer.android.com/studio#command-line-tools-only
    required: true
    default: "11076708"

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: cache
      with:
        key: android-${{ inputs.android-version }}-tools-${{ inputs.build-tools-version }}-cmd-${{ inputs.cmd-line-version }}-zip
        path: /opt/android

    - name: Installing…
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir --parents /opt/android

        ANDROID_HOME="/opt/android"
        ANDROID_SDK_ROOT="/opt/android"

        echo "Android Home: $ANDROID_HOME"
        echo "Android SDK root: $ANDROID_SDK_ROOT"

        # Install Android Command Line Tools
        curl -sSL "https://dl.google.com/android/repository/commandlinetools-linux-${CMD_LINE_VERSION}_latest.zip" -o /tmp/cmd-tools.zip
        unzip -q -d "$ANDROID_HOME" /tmp/cmd-tools.zip
        mv "$ANDROID_HOME"/cmdline-tools "$ANDROID_HOME"/latest
        mkdir "$ANDROID_HOME"/cmdline-tools
        mv "$ANDROID_HOME"/latest "$ANDROID_HOME"/cmdline-tools/latest

        # Install Android SDKs
        yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root="$ANDROID_HOME" || true
        "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --update --sdk_root="$ANDROID_HOME"
        "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --install --sdk_root="$ANDROID_HOME" \
               "build-tools;${BUILD_TOOLS_VERSION}" \
               "platforms;android-${ANDROID_VERSION}" \
               "platform-tools" \
               "extras;android;m2repository" \
               "extras;google;m2repository"
      env:
        ANDROID_VERSION: ${{ inputs.android-version }}
        BUILD_TOOLS_VERSION: ${{ inputs.build-tools-version }}
        CMD_LINE_VERSION: ${{ inputs.cmd-line-version }}

    - name: Exporting…
      shell: bash
      run: |
        {
          echo "ANDROID_HOME=/opt/android"
          echo "ANDROID_SDK_ROOT=/opt/android"
        } >> $GITHUB_ENV

        {
          echo "$ANDROID_HOME/tools"
          echo "$ANDROID_HOME/tools/bin"
          echo "$ANDROID_HOME/platform-tools"
          echo "$ANDROID_HOME/cmdline-tools/latest/bin"
        } >> $GITHUB_PATH

    - name: Testing…
      shell: bash
      run: sdkmanager --list
