name: '🧰 Chat Bot Commands'

on:
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-comment:
    name: Check comment
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.comment.body, '@github-actions[bot]') }}
    env:
      ACTOR: ${{ github.actor }}
      NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        if: ${{ contains(github.event.comment.body, 'dump') }}
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Say hello to @${{ github.actor }}
        if: ${{ contains(github.event.comment.body, 'hello') }}
        run: gh issue comment $NUMBER --body "Hi @$ACTOR!"
