name: '🤖 Commit and Push'

on: workflow_dispatch

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Hello, @$GITHUB_ACTOR!" --allow-empty
          git show
          git push
