name: 🤖 Testing setup-android

on: pull_request

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - uses: ./.github/actions/setup-android
